<definitions targetNamespace="nl.amis/workflow/IssuesService" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="nl.amis/workflow/IssuesService" xmlns:wfw="nl.amis/workflow" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <documentation>
        <abstractWSDL>http://soa2admin2.example.com:8001/soa-infra/services/default/IssuesService!1.0/WSDLs/IssuesService.wsdl</abstractWSDL>
    </documentation>
    <types>
        <xsd:schema>
            <xsd:import namespace="nl.amis/workflow" schemaLocation="XMLSchema_-589990623.xsd"/>
        </xsd:schema>
    </types>
    <message name="RetrieveIssuesRequestMessage">
        <part name="in" element="wfw:Request"/>
    </message>
    <message name="RetrieveIssuesResponseMessage">
        <part name="return" element="wfw:IssueList"/>
    </message>
    <portType name="IssuesService">
        <operation name="RetrieveIssues">
            <input message="tns:RetrieveIssuesRequestMessage"/>
            <output message="tns:RetrieveIssuesResponseMessage"/>
        </operation>
    </portType>
    <binding name="IssuesServiceBinding" type="tns:IssuesService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="RetrieveIssues">
            <soap:operation style="document" soapAction="RetrieveIssues"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="IssuesService">
        <port name="IssuesService_pt" binding="tns:IssuesServiceBinding">
            <soap:address location="http://soa2admin2.example.com:8001/soa-infra/services/default/IssuesService!1.0*soa_f9664b88-9747-4622-a516-ba4e0f6e53ae/IssuesService"/>
        </port>
    </service>
</definitions>